description: Configuration file for project template
author: Davide Vespasiani

##==========================##
##     Project I/O dirs     ##
##==========================##
project_config: {
    baseDir:  /stornext/General/data/user_managed/grpu_jchoi_0/projects/davide,
    project: project_template,
    datadir: data/,
    outdir: out/,
    logs: logs/,
    code: code/,
    pages: pages/,
    bin: bin/,
    utils: utils/,
    tmp_dir:  /vast/scratch/users/vespasiani.d/
}

##=============================##
## Parameters interactive sess ##  
##=============================##
interactive_sess: {
    ntasks: 1,
    threads: 1,
    cpus_per_task: 1,
    mem: 280G,
    time: 480,
    partition: regular,
    modules: config/modules.txt
}


##==========##
## Analyses ##  
##==========##
scripts: {
  rscripts: [analysis1,analysis3],
  pyscripts: [analysis2]
}


